chore: bring examples back into repository and add tests
libp2p/go-libp2p pull request #1092
Opened 2021-05-07 14:13 UTC by iand

Implements the approach discussed in #1052. Examples are now in a submodule with a replace directive that ensures they will be built using the version of go-libp2p in this repo.

Adds a test harness that enables some of the examples to be run as tests. The test harness reads log output and verifies expected log messages are present. Adding a test to an example is done by extracting the core of the example into a new function that can be called from main and from the harness. I have refactored a couple of examples to use helper functions to make them more amenable to external testing.

Fixes the relay example which was using relay discovery which was deprecated in 2020

Fixes libp2p/go-libp2p-examples#191

2021-05-07 14:14 UTC, iand commented
To ease review, this diff shows just changes made to add tests to examples: https://github.com/iand/go-libp2p/compare/iand:integrate-examples...iand:test-examples

2021-05-08 00:15 UTC, Stebalien requested changes

2021-05-08 05:06 UTC, Stebalien commented
Ok, tested with https://github.com/protocol/.github/pull/89.

2021-05-10 10:39 UTC, iand commented on .gitignore
> +.idea
I just followed existing style but will split into separate files

2021-05-10 10:44 UTC, iand commented on examples/.circleci/config.yml
> +version: 2
done

2021-05-10 10:44 UTC, iand commented on examples/LICENSE
> +The MIT License (MIT)
done

2021-05-10 10:45 UTC, iand commented on README.md
> +Examples can be found on the [examples folder](examples).
done

2021-05-10 10:46 UTC, iand commented on README.md
> -| [`go-libp2p-examples`](//github.com/libp2p/go-libp2p-examples) | [![Travis CI](https://travis-ci.com/libp2p/go-libp2p-examples.svg?branch=master)](https://travis-ci.com/libp2p/go-libp2p-examples) |
done

2021-05-12 14:11 UTC, marten-seemann approved these changes
Let's merge this, even though the Unified CI Setup is not done yet. Will fix that soon.

2021-05-12 14:12 UTC, merged