Close resource manager when host closes
libp2p/go-libp2p pull request #1343
Opened 2022-02-22 17:30 UTC by gammazero

When a host is closed, it should close its resource manager.  Otherwise, goroutines are leaked.

Generally this is not a problem when a host exists for the life of a program, but can be a problem if hosts are created and closed.

2022-02-22 17:30 UTC, willscott approved these changes

2022-02-22 17:58 UTC, vyzo requested changes
wait,no, there is a reason we havent done this. It is not necessary the case that we own the rcmgr; it could be shared between hosts in the app.

We can only safely close the default instantiation.

cc @marten-seemann

2022-02-22 18:00 UTC, willscott commented
whoops, sorry for the fast approval, i mistakenly thought this PR was up a level in application logic

2022-02-22 18:06 UTC, vyzo commented
no problem, we do want to close the default instantiation to avoid the
goroutine leak. If you can rework this to track that case, it would be
great.
Otherwise we'll sort it out with marten.

On Tue, Feb 22, 2022, 20:00 Will ***@***.***> wrote:

> whoops, sorry for the fast approval, i mistakenly thought this PR was up a
> level in application logic
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/libp2p/go-libp2p/pull/1343#issuecomment-1048065924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAI4SQQW3GXQRDG23NLADTU4PFLTANCNFSM5PCBLRIA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-03-31 09:46 UTC, marten-seemann commented
@gammazero Are you planning to fix this PR?

2022-04-01 11:57 UTC, gammazero commented
@marten-seemann I will fix it unless you plan to do so this week.

Would you prefer an additional option to tell `BasicHost` that is should assume ownership of the resource manager, or should BasicHost only close the resource manager if it is the default one?

2022-04-18 21:38 UTC, marten-seemann commented
I'm going to merge this PR. In fact, we have the same problem with the connection manager, and we also close it when the host closes.
This should get solved at some point, but it will probably require a bigger refactor of our host and services.

2022-04-18 21:38 UTC, merged