Added perPeerRateLimit env config
libp2p/go-libp2p pull request #1580
Opened 2022-05-31 13:26 UTC by millken

Fix #1579

2022-05-31 13:37 UTC, vyzo approved these changes

2022-05-31 16:23 UTC, marten-seemann commented
Not a big fan of making this configurable via environment variable.
The best fix would be to make the swarm injectable, and then use a constructor option. The next-better fix would be to have a package-level global variable.

2022-06-03 01:00 UTC, MarcoPolo commented
> Not a big fan of making this configurable via environment variable.
> The best fix would be to make the swarm injectable, and then use a constructor option. The next-better fix would be to have a package-level global variable.

Agreed. @millken mind making the package level global  change please? It’s better since then this is exposed prominently in the pkg reference, and your code can read your env var and set the variable.

2022-06-06 09:17 UTC, millken commented
> > Not a big fan of making this configurable via environment variable.
> > The best fix would be to make the swarm injectable, and then use a constructor option. The next-better fix would be to have a package-level global variable.
> 
> Agreed. @millken mind making the package level global change please? It’s better since then this is exposed prominently in the pkg reference, and your code can read your env var and set the variable.

Updated

2022-06-06 09:22 UTC, marten-seemann requested changes

2022-06-06 09:22 UTC, marten-seemann commented on config/config.go
> +	PerPeerLimit int
There's no way for a libp2p user to directly set values in this config.

2022-06-06 13:29 UTC, marten-seemann requested changes
I don't think we should have global config options for this. This seems overly specific.
Why don't you just add a variable, as @MarcoPolo suggested in https://github.com/libp2p/go-libp2p/pull/1580#issuecomment-1145483558.

2022-06-14 02:50 UTC, millken commented
> I don't think we should have global config options for this. This seems overly specific. Why don't you just add a variable, as @MarcoPolo suggested in [#1580 (comment)](https://github.com/libp2p/go-libp2p/pull/1580#issuecomment-1145483558).

Ok, Just change `const DefaultPerPeerRateLimit = 8` to `var DefaultPerPeerRateLimit = 8`

2022-06-14 23:33 UTC, MarcoPolo approved these changes

2022-06-14 23:53 UTC, merged

2022-06-14 23:53 UTC, MarcoPolo commented
Thanks!