add GenerateTestAddrs test
libp2p/go-libp2p pull request #1926
Opened 2022-12-01 07:31 UTC by tbal999

feel free to adjust this where necessary

this PR adds 1 table test to the core/test section of the repo

2022-12-01 08:54 UTC, marten-seemann commented
What’s motivating this PR? These functions are just used in tests.

2022-12-01 14:04 UTC, tbal999 commented
just thought "why not"

2022-12-06 04:55 UTC, marten-seemann requested changes
I'm still not convinced we actually need this, to be honest.

2022-12-06 04:55 UTC, marten-seemann commented on core/test/addrs_test.go
> +				"/ip4/1.2.3.4/tcp/2",
This assertion doesn't really make sense. The function would still be valid if the port numbers were different.

2022-12-06 04:55 UTC, marten-seemann commented on core/test/addrs_test.go
> +				outputStringArray = append(outputStringArray, actualOutput[index].String())
There's an `Equal` function on multiaddrs.

2022-12-07 07:40 UTC, tbal999 commented
If you are not convinced, feel free to close this.

2023-01-24 04:07 UTC, p-shahi commented
Thanks @tbal999 , going to close this. There are some other issues labled `good first issue` in case you'd like to contribute, we'd be happy to review.

2023-01-24 04:07 UTC, closed without merging