Add example for metrics and dashboard
libp2p/go-libp2p pull request #2232
Opened 2023-03-29 17:50 UTC by MarcoPolo

This came up after a call with @Giulio2002 when I discussed they could set up these dashboards for some more observability and to help debug #2202 . 

Note for reviewer: Could you please try this and make sure it works for you as well (follow instructions in README.md)

2023-04-02 17:35 UTC, lthibault requested changes

2023-04-02 17:35 UTC, lthibault commented on examples/metrics-and-dashboards/README.md
> +Go to http://localhost:3000/dashboards to see the dashboards.
Missing newline at EOF

2023-04-02 17:35 UTC, lthibault commented on examples/metrics-and-dashboards/go-libp2p-node.Dockerfile
> +ENTRYPOINT [ "/app/main" ]
Missing newline at EOF

2023-04-02 17:35 UTC, lthibault commented on examples/metrics-and-dashboards/grafana.Dockerfile
> +USER grafana
Missing newline at EOF

2023-04-03 06:00 UTC, sukunrt approved these changes
LGTM! :tada: 
I've added minor comments. Feel free to ignore them if you think they're not relevant

2023-04-03 19:25 UTC, sukunrt commented on examples/metrics-and-dashboards/main.go
> +	wg := sync.WaitGroup{}
*server initiate a connection with some clients.

2023-04-03 20:49 UTC, MarcoPolo commented on examples/metrics-and-dashboards/compose.yml
> +      - 3000:3000
I'm okay with that tradeoff

2023-04-11 01:52 UTC, MarcoPolo commented
Deferring this work until after ipfs thing

2023-06-01 08:51 UTC, marten-seemann commented
@MarcoPolo What's the status of this PR? It would be nice to get this merged before the next release.

2023-06-15 10:07 UTC, marten-seemann commented
@MarcoPolo Friendly ping. Can we push this PR across the finish line?

2023-06-16 00:41 UTC, MarcoPolo commented
Pushed changes, this is good to merge after CI passes.

2023-06-16 02:43 UTC, merged

2023-06-16 02:44 UTC, p-shahi commented
> Pushed changes, this is good to merge after CI passes.

merged based on this message, mainly in service of https://github.com/libp2p/blog/pull/77