feat(host): Error
libp2p/go-libp2p pull request #2331
Opened 2023-06-05 09:20 UTC by Wondertan

The goal here is to improve the experience of working with errors returned by the Host. With the current state, it's PITA to debug exactly what went wrong during a stream open and this feat attempts to solve it.

* Inspired by errors in std `net`.
* I wanted to improve the RoutedHost as well, but I will wait until you migrate to v1.20, as I need `errors.Join`
* I am open to any other suggestions on how to make this even better

2023-06-05 10:19 UTC, marten-seemann commented
I’m ok with the error wrapping changes introduced here. I’d like to be a little bit more careful about introducing a new error type here. Not saying that it’s a bad idea, but I’d prefer to have an issue and an API discussion first.

2023-06-05 10:40 UTC, Wondertan commented
>  I’d prefer to have an issue and an API discussion first.

My toxic trait is coming up with contributions out of nowhere 😄. 

Ok, let's make an issue!

2023-06-11 15:06 UTC, Wondertan commented
Any chance you can take a look at this?

2023-06-11 17:31 UTC, marten-seemann commented
> I’m ok with the error wrapping changes introduced here.

I already reviewed this PR. Let me know once you've updated it.

2023-06-12 16:46 UTC, Wondertan commented
Ok, it wasn't clear whether changes were requested or not

2023-06-13 10:32 UTC, Wondertan commented
Updated to keep wrappings only

2023-06-13 14:56 UTC, marten-seemann requested changes
... and so on for the other errors.

2023-06-13 14:56 UTC, marten-seemann commented on p2p/host/basic/basic_host.go
> +		return nil, fmt.Errorf("opening Network stream: %w", err)
```suggestion
		return nil, fmt.Errorf("failed to open stream: %w", err)
```

2023-06-13 14:56 UTC, marten-seemann commented on p2p/host/basic/basic_host.go
> +		return nil, fmt.Errorf("awating identify: %w", ctx.Err())
```suggestion
		return nil, fmt.Errorf("identify failed to complete: %w", ctx.Err())
```

2023-06-13 14:56 UTC, marten-seemann commented on p2p/host/basic/basic_host.go
> +			return nil, fmt.Errorf("negotiating protocol: %w", err)
```suggestion
			return nil, fmt.Errorf("failed to negotiate protocol: %w", err)
```

2023-06-13 14:56 UTC, marten-seemann commented on p2p/host/basic/basic_host.go
> +		return nil, fmt.Errorf("negotiating protocol: %w", ctx.Err())
```suggestion
		return nil, fmt.Errorf("failed to negotiate protocol: %w", ctx.Err())
```

2023-06-13 15:12 UTC, Wondertan commented
A user would usually wrap the error with "failed" or the log would also say that error, but I don't feel strongly about it, so applied.

2023-06-15 09:31 UTC, marten-seemann requested changes
@Wondertan Any reason you only changed ~half of the error messages?

2023-06-15 10:55 UTC, Wondertan commented
> @Wondertan Any reason you only changed ~half of the error messages?

I simply applied all the comments

2023-06-15 11:00 UTC, Wondertan commented
Fixed now

2023-06-27 18:21 UTC, merged