feat: Bring in gostream to the monorepo
libp2p/go-libp2p pull request #2521
Opened 2023-08-24 18:49 UTC by MarcoPolo

#2438 Builds on gostream. I think it would be good to bring it in to the monorepo.

2023-08-25 00:54 UTC, marten-seemann requested changes
This doesn't preserve Git history. Do you want me to use my repo consolidation script to do that?

2023-08-26 05:04 UTC, marten-seemann commented on p2p/gostream/conn.go
Should this go into `p2p/net` instead?

2023-08-28 20:07 UTC, MarcoPolo commented on p2p/gostream/conn.go
Done.

2023-08-28 20:09 UTC, MarcoPolo commented
I think this is simple enough that there isn't a ton to gain from the perspective of keeping history to help debug things.

2023-08-29 02:50 UTC, marten-seemann commented
> I think this is simple enough that there isn't a ton to gain from the perspective of keeping history to help debug things. But if you want to run your script, you are welcome to do so.

Probably not, I'd still prefer to preserve history. I don't see a good reason not to.

2023-08-30 09:51 UTC, closed without merging