identify: fix observed address handling
libp2p/go-libp2p pull request #2825
Opened 2024-06-07 03:18 UTC by ivan4th

If a connection was closed before receiving an identify response, the corresponding observed address could be wrongly removed as the connection counter for the local address was being decremented on each disconnect even if no messages were consumed by `IDService` previously.

2024-06-07 06:44 UTC, sukunrt requested changes
Oops! sorry about that!

I believe this smaller patch will fix the issue. 

```
diff --git a/p2p/protocol/identify/obsaddr.go b/p2p/protocol/identify/obsaddr.go
index 4437c4b0..fc1c100c 100644
--- a/p2p/protocol/identify/obsaddr.go
+++ b/p2p/protocol/identify/obsaddr.go
@@ -452,6 +452,12 @@ func (o *ObservedAddrManager) removeConn(conn connMultiaddrs) {
 	o.mu.Lock()
 	defer o.mu.Unlock()
 
+	observedTWAddr, ok := o.connObservedTWAddrs[conn]
+	if !ok {
+		return
+	}
+	delete(o.connObservedTWAddrs, conn)
+
 	// normalize before obtaining the thinWaist so that we are always dealing
 	// with the normalized form of the address
 	localTW, err := thinWaistForm(o.normalize(conn.LocalMultiaddr()))
@@ -467,11 +473,6 @@ func (o *ObservedAddrManager) removeConn(conn connMultiaddrs) {
 		delete(o.localAddrs, string(localTW.Addr.Bytes()))
 	}
 
-	observedTWAddr, ok := o.connObservedTWAddrs[conn]
-	if !ok {
-		return
-	}
-	delete(o.connObservedTWAddrs, conn)
 	observer, err := getObserver(conn.RemoteMultiaddr())
 	if err != nil {
 		return
```

2024-06-07 07:30 UTC, ivan4th commented
@sukunrt yes, that also fixes the problem, thanks!

Updated the PR

2024-06-07 08:42 UTC, sukunrt approved these changes
Thanks @ivan4th

2024-06-07 17:02 UTC, ivan4th commented
@MarcoPolo yes, that would help indeed, thank you!

2024-06-08 06:35 UTC, merged

2024-06-08 16:15 UTC, ivan4th commented
Oops, just noticed that when replacing my patch, I also reverted the testing code. Added it back in #2828