autorelay: send addresses on eventbus; dont wrap address factory
libp2p/go-libp2p pull request #3071
Opened 2024-11-29 09:57 UTC by sukunrt

Part of #2229

2025-02-06 00:09 UTC, MarcoPolo requested changes

2025-02-06 00:09 UTC, MarcoPolo commented on p2p/host/autorelay/autorelay_test.go
> +	require.Eventually(t, func() bool {
Prefer require.EventuallyWithT

2025-02-06 17:07 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +	emitter, err := host.EventBus().Emitter(new(event.EvtAutoRelayAddrs))
If we don't keep the autorelay reference, then yes.

2025-02-06 17:14 UTC, sukunrt commented on p2p/host/autorelay/addrsplosion.go
> +// TODO: Remove this, we don't need this. The current method tries to select the
will remove this in a follow up PR. Not related to the current change.

2025-02-06 17:14 UTC, sukunrt commented on config/config.go
>  	if err := cfg.addAutoNAT(bh); err != nil {
Nope. It works fine.

2025-02-06 17:25 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +func haveAddrsDiff(a, b []ma.Multiaddr) bool {
Nice! thanks.

2025-02-06 17:35 UTC, sukunrt commented on p2p/host/autorelay/autorelay_test.go
> +	require.Eventually(t, func() bool {
Is it for the fact that it collects errors and returns the last one?

2025-02-06 17:43 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +	if h.autoNat != nil && h.autorelay != nil && h.autoNat.Status() == network.ReachabilityPrivate {
Will take this up in a separate PR: 
https://github.com/libp2p/go-libp2p/issues/3172#issuecomment-2640568729

2025-02-07 14:02 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +	if opts.EnableAutoRelay {
The problem with this structure is that currently there's no way to get the autorelay object once it's constructed for debugging or any other reason.

I'm changing it though, let's make this change if we end up wanting access to this for debugging purposes.

2025-02-07 14:30 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +// This function computes the relay addrs when our status is private.
Changing it to just say computes the node's address. It can return an empty list when we have no reservations.

2025-02-07 14:43 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +	emitter, err := host.EventBus().Emitter(new(event.EvtAutoRelayAddrs))
I'm always a bit scared of a design where you have to send the updates exactly correctly in order. But will revisit this if we run in to a bug.

2025-02-07 15:46 UTC, sukunrt commented on config/config.go
>  	if err := cfg.addAutoNAT(bh); err != nil {
Removing this change though. It's unrelated.

2025-02-13 21:11 UTC, MarcoPolo commented on p2p/host/basic/basic_host.go
> +	if opts.EnableAutoRelay {
I don't think I understand. Could you use [`fx.Populate`](https://pkg.go.dev/go.uber.org/fx#Populate)?

2025-02-13 21:11 UTC, MarcoPolo commented on p2p/host/autorelay/autorelay_test.go
> +	require.Eventually(t, func() bool {
yes

2025-02-13 21:40 UTC, MarcoPolo commented on p2p/host/basic/basic_host.go
> +	relayAddrs atomic.Value
Slight preference to using the atomic.Pointer type since it's a little nicer to use.

2025-02-14 06:15 UTC, MarcoPolo approved these changes
Just a couple small comments

2025-02-14 06:15 UTC, MarcoPolo commented on p2p/host/autorelay/relay_finder.go
> +	if len(raddrs) > maxRelayAddrs {
may as well do this check in the loop above too.

2025-02-14 06:15 UTC, MarcoPolo commented on p2p/host/autorelay/relay_finder.go
> +			case <-hi.IDService().IdentifyWait(conn):
Ideally we'd do something like the draft conntracker logic to see which connections supports relaying. In practice this is probably fine as a relay server likely relays on all connections.

2025-02-14 06:15 UTC, MarcoPolo commented on p2p/host/autorelay/autorelay_test.go
> +		for _, r := range relays[1:] {
nit, this can move out of the eventually loop

2025-02-17 12:11 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +	if opts.EnableAutoRelay {
Thanks for fx.Populate, but that will need #2962 

My point was. Once you create a host, `host, err := libp2p.New()`, There's no way to access the `AutoRelay` object now for debugging purposes.

2025-02-17 15:48 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +	addrs = slices.Clone(h.AddrsFactory(addrs))
I'll take that in a separate PR.

2025-02-17 15:49 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +	if len(raddrs) > maxRelayAddrs {
We need to sort before limiting to the desired value to keep the list stable.

2025-02-17 15:54 UTC, sukunrt commented on p2p/host/autorelay/relay_finder.go
> +			case <-hi.IDService().IdentifyWait(conn):
Hmm, this is tricky indeed. It needs #2693 and maybe the ability to connect only on specific transports and not on everything in the peerstore.

2025-02-18 13:06 UTC, merged