addressservice: extract out addressing logic from basichost
libp2p/go-libp2p pull request #3075
Opened 2024-12-01 13:37 UTC by sukunrt

The goal is to keep modifying it and removing the dependency on basichost by relying on events. At that point, we can expose this as a separate service usable by both basic and blank hosts

2025-01-30 23:31 UTC, MarcoPolo requested changes
I know the worst bits of this code are just copied over from the previous implementation. So apologies for picking too much into those.

This is a good point to remove some of the idiosyncrasies here.

2025-01-30 23:31 UTC, MarcoPolo commented on p2p/host/basic/address_service.go
> +			result = append(result, a.observedAddrsService.OwnObservedAddrs()...)
Would it be better to use OwnObservedAddrFor per listen Addr? Seems surprising
that if we haven't discovered our nat we return all our observed addrs. Example:
It would be surprising if I called this method with just QUIC and got
back a tcp multiaddr.

2025-01-30 23:31 UTC, MarcoPolo commented on p2p/host/basic/address_service.go
> +			result = append(result, ma.Join(ip, extMaddrNoIP))
So we expect to have a valid external port mapping from the nat service, but be given a private IP Address, and we expect the that second NAT somehow preserves that port mapping? Does this actually work?

2025-01-30 23:31 UTC, MarcoPolo commented on p2p/host/basic/address_service.go
> +func (a *addressService) AllAddrs() []ma.Multiaddr {
Related. We should spend a bit of time thinking if these are the names we want
for these methods now while we're refactoring.

2025-01-30 23:31 UTC, MarcoPolo commented on p2p/host/basic/address_service.go
> +	return slices.DeleteFunc(addrs, func(a ma.Multiaddr) bool { return !manet.IsPublicAddr(a) })
Is there any sorting that we want to do here?

2025-02-22 14:27 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +func (a *addressService) AllAddrs() []ma.Multiaddr {
I am deferring API for follow up PRs. This PR is a bit too large. 
For the time being: 
Changed this to `DirectAddrs` and also these methods aren't exposed to users so we can change the naming later.

2025-02-22 14:27 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +// to the `listenAddr`
refactored this a bit. Does the new one read better?

2025-02-22 14:29 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +	if !h.disableSignedPeerRecord {
It now depends on the Addrs method from the `addrsManager`. It's also better to do the sideeffects(persisting the peerstore in this case) to after the host is completely initialized.

2025-02-22 14:30 UTC, sukunrt commented on p2p/host/basic/basic_host.go
>  // this will only have host's private, relay, and no public addresses.
It is. Will be taken up with #3172

2025-02-22 14:30 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +		autoRelayAddrsSub:    addrSub,
moved these to background.

2025-02-22 14:32 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +func (a *addressService) AddrsUpdated() chan struct{} {
It's only intended to be used by the host for updating the peer record and sending the current addrs change event. 
The event is still on the host because I intend to deprecate it in a follow up PR. 

This struct is not exported. It's only intended to be used for the host. Should we change this to updatePeerRecordChan to make it clear that that's the only use of this?

2025-02-22 14:33 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +	prevmap := make(map[string]struct{})
changed it to use unique and sort. That was much faster.

2025-02-22 14:34 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +	currmap := make(map[string]struct{})
Yup. This was much better. Thanks!

2025-02-22 14:34 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +		case <-a.autoRelayAddrsSub.Out():
moved it.

2025-02-22 14:34 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +	// Add certhashes for the addresses provided by the user via address factory.
how? It's used in the line, `addrs = slices.Clone(a.addrsFactory(addrs))`, no?

2025-02-22 14:35 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +			result = append(result, a.observedAddrsService.OwnObservedAddrs()...)
That's fair. This uses each listen addr now individually.

2025-02-22 14:36 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +			result = append(result, ma.Join(ip, extMaddrNoIP))
I've changed this to just use the addr for obsaddr manager. My intention initially was to not change any behavior since this PR is large as it is anyway.

2025-02-22 14:37 UTC, sukunrt commented on p2p/host/basic/address_service.go
> +	return slices.DeleteFunc(addrs, func(a ma.Multiaddr) bool { return !manet.IsPublicAddr(a) })
I'm explicitly sorting now. I think we should make it an API guarantee in `unique` that it'll sort addresses. unique does currently sort addresses so that's one unnecessary sort.

2025-02-25 04:27 UTC, MarcoPolo commented on p2p/host/basic/address_service.go
> +	// Add certhashes for the addresses provided by the user via address factory.
Sorry. The sentence is ambiguous, and my comment was also ambiguous. I read it as "add certhashes ... via the address factory" rather than "add certhashes for the (addresses provided by the address factory)". It's fine to leave it as is since that's how it is currently, but a reword would be appreciated.

2025-02-25 04:48 UTC, MarcoPolo commented on p2p/host/basic/addrs_manager.go
> +	slices.SortFunc(addrs, func(a, b ma.Multiaddr) int { return bytes.Compare(a.Bytes(), b.Bytes()) })
Once you rebase or merge master, you can use Multiaddr.Compare here

2025-02-25 05:17 UTC, MarcoPolo approved these changes
A couple small things, but looks good

2025-02-25 05:17 UTC, MarcoPolo commented on p2p/host/basic/basic_host.go
> +	n.Notify(&network.NotifyBundle{
The address manager implements this interface, did you mean to use it?

2025-02-25 05:17 UTC, MarcoPolo commented on p2p/host/basic/basic_host.go
> +		rec, err := h.makeSignedPeerRecord(h.addressManager.Addrs())
We need to do this in NewHost and Start?

2025-02-25 05:17 UTC, MarcoPolo commented on p2p/host/basic/addrs_manager_test.go
> +			Expected: []ma.Multiaddr{ma.StringCast("/ip4/1.1.1.1/udp/10/quic-v1")},
Is this really what we should expect? Why doesn't the observed address take
precedence here?

2025-02-25 18:13 UTC, MarcoPolo commented
>  @MarcoPolo Do you think we should be defensive and parse return values form each of those components here and filter for nil etc?

Can you expand a bit on what you mean here please?

2025-02-27 15:59 UTC, sukunrt commented
>Can you expand a bit on what you mean here please?

I'm not filtering the return value from observed addrs manager and nat manager for nils.

2025-02-27 16:00 UTC, sukunrt commented on p2p/host/basic/addrs_manager_test.go
> +			Expected: []ma.Multiaddr{ma.StringCast("/ip4/1.1.1.1/udp/10/quic-v1")},
Current behaviour. It's reasonable to change this though.

2025-02-27 16:01 UTC, sukunrt commented on p2p/host/basic/addrs_manager_test.go
> +			Expected: []ma.Multiaddr{ma.StringCast("/ip4/1.1.1.1/udp/10/quic-v1")},
https://github.com/libp2p/go-libp2p/issues/3214

2025-02-27 16:07 UTC, sukunrt commented on p2p/host/basic/basic_host.go
> +		rec, err := h.makeSignedPeerRecord(h.addressManager.Addrs())
After start definitely. Not sure if we need it just after NewHost, but that's the current behavior.

2025-02-27 16:23 UTC, sukunrt commented on p2p/host/basic/addrs_manager.go
> +	return dst
It's done eventually in the main loop. Limited the observed addrs to 5 per listen address.

2025-02-27 16:54 UTC, merged